services:
  vault:
    image: hashicorp/vault:1.16.2
    command: server
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - /opt/vault/config:/vault/config
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - GOOGLE_APPLICATION_CREDENTIALS=/vault/config/credentials.json
    cap_add:
      - IPC_LOCK
